SELECT PRODUCT_ID, PRODUCT_NAME, PRODUCT_CD, CATEGORY, PRICE
FROM FOOD_PRODUCT
WHERE PRICE = (SELECT MAX(PRICE) FROM FOOD_PRODUCT);
-- (SELECT MAX(PRICE) FROM FOOD_PRODUCT) : FOOD_PRODUCT 테이블에서 최대 가격을 찾는 서브쿼리
-- 즉, 전체 상품 중에서 가장 비싼 가격과 동일한 가격을 가진 상품만 조회