# 서브 쿼리 사용
# -> July 테이블에 같은 FLAVOR가 여러 행에 존재
SELECT fh.FLAVOR 
FROM FIRST_HALF fh
INNER JOIN (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
    FROM JULY
    GROUP BY FLAVOR
) f ON fh.FLAVOR = f.FLAVOR
ORDER BY fh.TOTAL_ORDER + IFNULL(f.TOTAL_ORDER, 0) DESC
LIMIT 3;