SELECT
    DISTINCT(C.CAR_ID)
FROM
    CAR_RENTAL_COMPANY_CAR C,
    CAR_RENTAL_COMPANY_RENTAL_HISTORY RH
WHERE
    C.CAR_ID = RH.CAR_ID AND
    C.CAR_TYPE = "세단" AND
    RH.START_DATE >= "2022-10-01"
ORDER BY
    C.CAR_ID DESC;
    