SELECT
    b.CATEGORY, SUM(SALES) AS TOTAL_SALES
FROM
    BOOK b, BOOK_SALES bs
WHERE
    b.BOOK_ID = bs.BOOK_ID AND
    bs.SALES_DATE >= "2022-01-01" AND 
    bs.SALES_DATE < "2022-02-01"
GROUP BY
    b.CATEGORY
ORDER BY 
    b.CATEGORY;